### ISSUE TITLE
Release to jcenter

### ISSUE THREAD

**Issue by RichoDemus** [OSSIndex/ossindex-gradle-plugin#2]
It seems like this plugin is not available in jcenter, it would be really neat if it were :)

https://jcenter.bintray.com/net/ossindex/ossindex-gradle-plugin/ responds with 404

**Comment by RichoDemus** [comment]
Or is it even in maven central, can't seem to find it there either, is there a published release of this plugin? :)

**Comment by RichoDemus** [comment]
I just saw this in the readme: TODO (the plugin is yet to be released)

I apologize :)

**Comment by MarkusAmshove** [comment]
I'll reopen this issue for visibility :-)

I'll do a few more tests and release the first version within this week, since we're (aside from generating a report) on the same features as the maven plugin

**Comment by MarkusAmshove** [comment]
@RichoDemus I uploaded a version to the gradle plugin repository, instructions can be found in the [readme](https://github.com/OSSIndex/ossindex-gradle-plugin#installing).

I've accidentally uploaded a "SNAPSHOT" version which Gradle doesn't support without specifying the version. (the deletion of the snapshot version is pending)

I've tested using the 0.1.0 version in multiple Projects and ist working :)

**Comment by RichoDemus** [comment]
I gave it a quick go and it seems to work really well (found a vulnerability too! 👍 )

Thanks a lot for your time :)

**Comment by MarkusAmshove** [comment]
Gradle has removed the snapshot Version, so it will work as expected now :-)
