### ISSUE TITLE
What's the difference between this plugin vs owasp dependency checker?

### ISSUE THREAD

**Issue by amimas** [OSSIndex/ossindex-gradle-plugin#26]
Hello,

This plugin seems interesting. Would you be able to tell me how is this different from the following dependency checker plugin?

https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html

Is this an alternative to the above mentioned plugin or does it provide different typea of insights?

**Comment by ken-duck** [comment]
That will be interesting to see, actually. Till recently it was an alternative, as we provide data from a different data source (not only NVD, but also other advisory sites as well as our own custom researched data). In addition we connect CVEs with packages in a different manner than DependencyCheck. Contrariwise DependencyCheck can identify vulnerable files that are not even in packages, whereas this plugin is only looking at dependencies.

The reason I mention it will be interesting to see, we are hoping to help add OSS Index support to OWASP DependencyCheck, which means it will have access to all of the data that we are making available. I cannot comment on the impact the different package-matching schemes will have at this time, however.

**Comment by ken-duck** [comment]
However, by "alternative" I don't mean "use OSS Index instead of DependencyCheck". They operate in different manners and as mentioned above, somewhat different data sets. The best way forward could be to use both, as you might find the data from one complements the other.

**Comment by ken-duck** [comment]
It seems that the OSS Index integration with DependencyCheck has been merged!

https://github.com/jeremylong/DependencyCheck/pull/1771#issuecomment-475868641

It has been merged with master, and appears to have the `ossindexAnalyzerEnabled` analyzer configuration option added.
