### ISSUE TITLE
Plugin doesn't appear to work in parallel builds

### ISSUE THREAD

**Issue by art-bjss** [OSSIndex/ossindex-gradle-plugin#29]
It seems that running multiple `audit` tasks and `--parallel` results in an inaccurate `junitReport.xml` file being generated with only single task's output.

**Comment by ken-duck** [comment]
Agh. Bummer. Thanks for the report. We are currently working through a few new issues as a result of the recent move to the new OSS Index REST API. Once those are cleared out I will see what can be done here.

**Comment by ken-duck** [comment]
My completely uneducated guess is that we might be dealing with *completely* separate processes which are would almost certainly lead to the file being overwritten. It will be "interesting" to solve if that is the case.

**Comment by art-bjss** [comment]
I did try 

```
  audit {
        junitReport = "junitReport${project.name}.xml"
```

But that resulted in only a single `junitReport-some-project-name.xml` file being generated, rather than multiple ones

**Comment by aparsons** [comment]
I can confirm this is still an issue with 0.4.5-beta. I have a multi-module gradle project and when running the audit task with `org.gradle.parallel=true` there are file locking errors.

Running the task with `-Dorg.gradle.parallel=false` will allow the audit to successfully run.

**Comment by ken-duck** [comment]
Very curious. Thanks for the hint on how to work around the problem. I have been working on issues in some of the other clients, but may be able to wrangle some time this week.

Do you happen to know of an open source project which has a parallel build that exhibits this behaviour? I will try assembling a simple project by hand to reproduce the problem meanwhile.

**Comment by ken-duck** [comment]
Just an update to let you know I have not forgotten. The new year started rather chaotically for me, but I am catching up on things so should be able to take a poke at this soon.

**Comment by ken-duck** [comment]
Quick update. I have reproduced the problem, and am now working on a solution.

**Comment by ken-duck** [comment]
Pushed a new release to both GitHub and Gradle: https://github.com/OSSIndex/ossindex-gradle-plugin/releases/tag/v0.4.6-beta

If this resolves your problem please let me know. Thanks!

**Comment by ken-duck** [comment]
Closing for now, as there have been tests and reports that this is working.

A new (related) request has been created, but it involves completely separate builds running as separate unix processes, and not just separate gradle processes: https://github.com/OSSIndex/ossindex-gradle-plugin/issues/39
