### ISSUE TITLE
Exclusions: Advanced vulnerability management doesn't work

### ISSUE THREAD

**Issue by anasoid** [OSSIndex/ossindex-gradle-plugin#31]
when add configuration exclude packages build failed
gradle version : 4.9

  build file '.......build.gradle': 32: Statement labels may not be used in build scripts.
  In case you tried to configure a property named 'packages', replace ':' with '=' or ' ', otherwise it will not have the desired effect.
   @ line 32, column 19.
             packages: [ 'org.dependency:thelibrary:1.0.0' ]
                       ^

  1 error

**Comment by ken-duck** [comment]
Could you post the text surrounding the packages line? It must be within a similar structure to this:

```
audit {
    exclusion = {
        packages: [ 'org.dependency:thelibrary:1.0.0' ]
    }
}
```

Where there is an audit section (with no equals sign), containing the exclusion section (with the equals sign), containing the packages list (with the colon).

The audit section may contain other OSS Index plugin settings.

**Comment by anasoid** [comment]
thanks you for interesting to my post.

The config is on the root of file, it work perfectly with ignore.
with exactly this text (without version)

audit {
    exclusion = {
        packages: [ 'org.dependency:thelibrary' ]
    }
}

**Comment by ken-duck** [comment]
I should have checked the last time. What version of the plugin are you using? For exclusions it should be [0.4.5-beta](https://plugins.gradle.org/plugin/net.ossindex.audit)

A non-beta version will be published soon.

**Comment by ken-duck** [comment]
Oh heck. The documentation is wrong, sorry :(

The "exclusion" should not have an equals.

Here are a couple of samples of valid exclusions:

```
audit {
    exclusion {
        vid = 'c655734e-0c42-4de8-a3d8-8496b541ee96'
        packages = [
                'org.grails/grails:2.0.1'
        ]
    }
    exclusion {
        packages = [
                'org.grails/grails:2.0.1'
        ]
    }
    exclusion {vid = '96a6fc01-c9c1-4098-94e5-c30f4052a3d4'}
}
```

**Comment by ken-duck** [comment]
The online docs look correct. Please let me know if you are still having troubles.

**Comment by ken-duck** [comment]
Closing, as it seems the advanced management works.
