### ISSUE TITLE
build does not stop when audit ignore is in gradle

### ISSUE THREAD

**Issue by TomDePauw** [OSSIndex/ossindex-gradle-plugin#4]
hello from the moment you put something like this in the code:
```
audit {
    ignore = ['javax.mail:mail:1.4']
}
```
every other issue does not stop the build 

> BUILD SUCCESSFUL

 while expecting when other libraries have issue that are not ignored

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':core:audit'.
> > Too many vulnerabilities (16) found.

**Comment by MarkusAmshove** [comment]
I resolved the issue and wrote a [test](https://github.com/OSSIndex/ossindex-gradle-plugin/blob/master/src/test/groovy/net/ossindex/integrationtests/OssIndexAuditPluginTests.groovy#L166) for it.

Version 0.1.1 of the plugin should fix this. could you try this on your end? :-)

**Comment by TomDePauw** [comment]
hello, thanks, but it does not seem to fail the build, i went from

> 6 unignored (of 15 total) vulnerabilities found
> 
> BUILD SUCCESSFUL

to

> 0 unignored (of 15 total) vulnerabilities found
> 
> BUILD SUCCESSFUL

**Comment by MarkusAmshove** [comment]
Can you post your build.gradle?
