### ISSUE TITLE
README.md out of sync with Code

### ISSUE THREAD

**Issue by effad** [OSSIndex/ossindex-gradle-plugin#42]
README.md has the following example:
```
audit {
    exclusion {
        id = '96a6fc01-c9c1-4098-94e5-c30f4052a3d4'
    }
}
```
which doesn't work, `id` needs to be `vid` I think

**Comment by ken-duck** [comment]
Whoops. You are indeed correct. Thanks for pointing this out.
Fixed in https://github.com/OSSIndex/ossindex-gradle-plugin/commit/f5c6db1d61245f827e3ec17e3c4eeff3ee45d002
