### ISSUE TITLE
Feature request Ignore cve-errors

### ISSUE THREAD

**Issue by TomDePauw** [OSSIndex/ossindex-gradle-plugin#7]
Hallo, thanks for you great work.
I would like to ask for a new feature. Do you think it would be possible to ignore issues based on their cve number.

**Comment by MarkusAmshove** [comment]
I've opened a new issue to try to find a good way to merge the existing proposals about ignoring specific stuff. #8 

I'm pretty busy in June but I'll can get to it in July.

If there are any further features you'd like to see about ignoring stuff, please discuss :-)

**Comment by TomDePauw** [comment]
Thanks for you quick reply.

**Comment by ken-duck** [comment]
I have put together a short Wiki document to track some ideas taken from this and several other issues: https://github.com/OSSIndex/ossindex-gradle-plugin/wiki/Advanced-Ignore-Functionality

As a first step I will be implementing a Utility class/method which will be used to perform the filtering itself (and some test code). *Then* I will be implementing the config file fields required to control the filtering.

Comments and edits on the wiki alternatively on the issues themselves are welcome. Once I have a start to the code I will make a pull request which can be a single location for the discussion.

**Comment by ken-duck** [comment]
At long last the features have left "beta" and are official. The newest (non-beta) version is 0.3.21, with documentation on more advanced vulnerability exclusions described here: https://github.com/OSSIndex/ossindex-gradle-plugin#alpha-exclusions-advanced-vulnerability-management

Sorry for the delay in notification of this feature.

I will also take this opportunity to mention that there is a rather major release incoming which will be adding support for the OSS Index v3 REST API, which provides access to a new database with many more vulnerabilities and is being actively maintained.

**Comment by ken-duck** [comment]
I will also note at this time that moving to the new API (when available) will mean that vulnerability IDs are changing since the new API uses UUIDs. This is a one time change: we don't intend on changing IDs again.
